# Generated by Django 3.2.6 on 2022-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('type', models.CharField(default='', max_length=4)),
            ],
        ),
    ]
