# Generated by Django 4.0.6 on 2022-07-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_temproraryupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemproraryUpload',
            new_name='TemproraryFile',
        ),
    ]
