# Generated by Django 4.0.6 on 2022-07-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_temproraryupload_temproraryfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemproraryFile',
        ),
    ]
